name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for SonarCloud to detect history

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          organization: ubaida10
          projectKey: 10pearls_10Pearls-Shine-Internship-Project
          token: ${{ secrets.SONAR_TOKEN }}
          extra-properties: |
            sonar.branch.name=main
            sonar.sources=.
